import type { Category, LocalizedText, Product, ProductDetailTable } from "./products"

type LocalizedName = [ru: string, kz: string, en: string]

const localized = (ru: string, kz: string, en: string): LocalizedText => ({ ru, kz, en })

const technical = (value: string): LocalizedText => localized(value, value, value)

const detailTable = (
  title: LocalizedText,
  columns: LocalizedText[],
  rows: LocalizedText[][],
): ProductDetailTable => ({ title, columns, rows })

const descriptions: Record<Category, Product["description"]> = {
  chemistry: {
    ru: "Промышленный химический реагент. Марка, концентрация и технические характеристики подбираются под требования заказчика.",
    kz: "Өнеркәсіптік химиялық реагент. Маркасы, концентрациясы және техникалық сипаттамалары тапсырыс берушінің талаптарына сай таңдалады.",
    en: "Industrial chemical reagent. Grade, concentration, and technical specifications are selected to meet customer requirements.",
  },
  metals: {
    ru: "Металлопродукция промышленного назначения. Марка материала, размеры и исполнение подбираются по техническому заданию.",
    kz: "Өнеркәсіптік мақсаттағы металл өнімі. Материал маркасы, өлшемдері және орындалуы техникалық тапсырма бойынша таңдалады.",
    en: "Industrial metal product. Material grade, dimensions, and configuration are selected according to the technical specification.",
  },
  equipment: {
    ru: "Промышленное оборудование или комплектующая. Комплектация и технические параметры подбираются под условия эксплуатации.",
    kz: "Өнеркәсіптік жабдық немесе құрамдас бөлшек. Жинақталуы мен техникалық параметрлері пайдалану жағдайына сай таңдалады.",
    en: "Industrial equipment or component. Configuration and technical parameters are selected for the operating conditions.",
  },
  rubber: {
    ru: "Резинотехническая продукция промышленного назначения. Исполнение и параметры подбираются под условия эксплуатации.",
    kz: "Өнеркәсіптік мақсаттағы резеңке-техникалық өнімдер. Орындалуы мен параметрлері пайдалану жағдайына сай таңдалады.",
    en: "Industrial rubber products. Configuration and specifications are selected for the operating conditions.",
  },
}

function product(
  id: string,
  category: Category,
  name: LocalizedName,
  origin: string,
  buyer: string,
  formula?: string,
  image?: string,
): Product {
  return {
    id,
    category,
    name: { ru: name[0], kz: name[1], en: name[2] },
    description: descriptions[category],
    origin,
    buyer,
    formula,
    image,
  }
}

export const spreadsheetProducts: Product[] = [
  // Chemical reagents selected in green in the source workbook.
  product("sheet-chem-1", "chemistry", ["Сода каустическая", "Каустикалық сода", "Caustic soda"], "Китай", "АГМК, НГМК, ТЭЦ", "NaOH"),
  product("sheet-chem-3", "chemistry", ["Уголь активированный", "Белсендірілген көмір", "Activated carbon"], "Вьетнам/Индия", "НГМК, Казцинк", "C"),
  product("sheet-chem-4", "chemistry", ["МИБК", "МИБК", "MIBK"], "Франция/Китай", "АГМК", "C₆H₁₂O", "/images/МИБК.jpg"),
  product("sheet-chem-5", "chemistry", ["Флотореагент", "Флотациялық реагент", "Flotation reagent"], "Россия", "АГМК, НГМК", "Смесь", "/images/флотореагент.jpg"),
  product("sheet-chem-6", "chemistry", ["Тиомочевина", "Тиомочевина", "Thiourea"], "Китай", "АГМК, НГМК", "CH₄N₂S", "/images/тиомочевина.jpg"),
  product("sheet-chem-7", "chemistry", ["Цианистый натрий", "Натрий цианиді", "Sodium cyanide"], "Китай", "АГМК", "NaCN"),
  product("sheet-chem-8", "chemistry", ["Собиратель", "Жинағыш реагент", "Collector reagent"], "Китай", "АГМК", "Смесь", "/images/собиратель.jpg"),
  product("sheet-chem-9", "chemistry", ["Смола ионообменная для добычи золота и урана", "Алтын мен уран өндіруге арналған ионалмасу шайыры", "Ion-exchange resin for gold and uranium recovery"], "Китай", "АГМК, НГМК, Минэнерго", "Полимер", "/images/смолаионообменная.jpg"),
  product("sheet-chem-10", "chemistry", ["Смола для водоочистки (аналоги АВ-17-8, КУ-2-8, АН-31)", "Су тазартуға арналған шайыр (АВ-17-8, КУ-2-8, АН-31 баламалары)", "Water-treatment resin (equivalents of AV-17-8, KU-2-8, AN-31)"], "Китай/Россия", "Минэнерго", "Полимер", "/images/Смола_для_водоочистки.jpg"),
  product("sheet-chem-13", "chemistry", ["Флокулянты Praestol, Airo, Cyquest, Nalco", "Praestol, Airo, Cyquest, Nalco флокулянттары", "Praestol, Airo, Cyquest, and Nalco flocculants"], "Китай", "НГМК", "Полимер", "/images/Флокулянты_Praestol_Airo_Cyquest_Nalco.jpg"),
  product("sheet-chem-14", "chemistry", ["Медный купорос", "Мыс купоросы", "Copper sulfate"], "Узбекистан", "Казцинк", "CuSO₄·5H₂O"),
  product("sheet-chem-15", "chemistry", ["Нитрат свинца", "Қорғасын нитраты", "Lead nitrate"], "Китай", "НГМК", "Pb(NO₃)₂", "/images/Нитрат_свинца.jpg"),
  product("sheet-chem-20", "chemistry", ["Ингибитор ИОМС", "ИОМС ингибиторы", "IOMS inhibitor"], "Россия", "АГМК", "Смесь", "/images/Ингибитор_ИОМС.jpg"),
  product("sheet-chem-21", "chemistry", ["Реагент Оптион", "Option реагенті", "Option reagent"], "Россия", "АГМК", "Смесь", "/images/Реагент_Оптион.jpg"),
  product("sheet-chem-22", "chemistry", ["Реагенты для печи ПЖВ", "ПЖВ пешіне арналған реагенттер", "Reagents for PZhV furnace"], "Германия", "АГМК", "Смесь", "/images/Реагенты_для_печи_ПЖВ.jpg"),
  product("sheet-chem-23", "chemistry", ["Винипласт листовой", "Табақ винипласт", "Vinyl plastic sheet"], "Китай", "АГМК", "(C₂H₃Cl)ₙ", "/images/Винипласт_листовой.jpg"),
  product("sheet-chem-24", "chemistry", ["Гидросульфит натрия", "Натрий гидросульфиті", "Sodium dithionite"], "Китай", "АГМК", "Na₂S₂O₄", "/images/Гидросульфит натрия.jpg"),
  product("sheet-chem-25", "chemistry", ["Перекись натрия", "Натрий пероксиді", "Sodium peroxide"], "Китай / Франция", "АГМК", "Na₂O₂", "/images/Перекись_натрия.jpg"),
  product("sheet-chem-26", "chemistry", ["Медь фосфористая", "Фосфорлы мыс", "Phosphor copper"], "Китай", "АГМК", "Cu–P", "/images/Медь_фосфористая.jpg"),
  product("sheet-chem-27", "chemistry", ["Клей костный", "Сүйек желімі", "Bone glue"], "Китай", "АГМК", "Белковая смесь", "/images/Клей_костный.jpg"),
  product("sheet-chem-28", "chemistry", ["Сульфид натрия", "Натрий сульфиді", "Sodium sulfide"], "Китай", "АГМК", "Na₂S", "/images/Сульфид_натрия.jpg"),
  product("sheet-chem-29", "chemistry", ["Гипохлорит кальция", "Кальций гипохлориті", "Calcium hypochlorite"], "Китай", "АГМК", "Ca(ClO)₂", "/images/Гипохлорит_кальция.jpg"),
  product("sheet-chem-30", "chemistry", ["Гидразин сернокислый", "Гидразин сульфаты", "Hydrazine sulfate"], "Китай", "АГМК", "N₂H₆SO₄", "/images/гидразин_сернокислый.jpg"),
  product("sheet-chem-31", "chemistry", ["Силикокальций", "Силикокальций", "Calcium silicide alloy"], "Китай", "АГМК, НГМК", "Ca–Si", "/images/силикокальций.jpg"),
  product("sheet-chem-32", "chemistry", ["Фурфуриловый спирт", "Фурфурил спирті", "Furfuryl alcohol"], "Китай", "АГМК", "C₅H₆O₂", "/images/Фурфуриловый_спирт.jpg"),
  product("sheet-chem-33", "chemistry", ["Силикагель", "Силикагель", "Silica gel"], "Россия", "АГМК", "SiO₂·nH₂O", "/images/Силикагель.jpg"),
  product("sheet-chem-34", "chemistry", ["Лакокрасочная продукция", "Бояу-лак өнімдері", "Paint and coating products"], "Россия", "АГМК", "Смесь", "/images/Лакокрасочная_продукция.jpg"),
  product("sheet-chem-35", "chemistry", ["Триполифосфат натрия", "Натрий триполифосфаты", "Sodium tripolyphosphate"], "Казахстан", "АГМК", "Na₅P₃O₁₀", "/images/Триполифосфат_натрия.jpg"),
  product("sheet-chem-36", "chemistry", ["Олеиновая кислота", "Олеин қышқылы", "Oleic acid"], "Китай", "АГМК", "C₁₈H₃₄O₂", "/images/Олеиновая_кислота.jpg"),
  product("sheet-chem-37", "chemistry", ["Трёхсернистая сурьма", "Сурьма трисульфиді", "Antimony trisulfide"], "Китай/Россия", "АГМК", "Sb₂S₃", "/images/Трёхсернистая_сурьма.jpg"),
  product("sheet-chem-39", "chemistry", ["Микросфера", "Микросфера", "Microspheres"], "Китай/Франция", "АГМК", "Минеральный состав", "/images/Микросфера.jpg"),
  product("sheet-chem-44", "chemistry", ["Текстолит", "Текстолит", "Textolite laminate"], "Китай/Россия", "АГМК", "Композит", "/images/Текстолит.jpg"),
  product("sheet-chem-45", "chemistry", ["Натрий кремнефтористый", "Натрий кремнийфториді", "Sodium hexafluorosilicate"], "Китай", "АГМК", "Na₂SiF₆", "/images/Натрий_кремнефтористый.jpg"),
  product("sheet-chem-46", "chemistry", ["Противопригарное покрытие", "Күйікке қарсы жабын", "Anti-burn coating"], "Россия/Китай", "АГМК", "Смесь", "/images/Противопригарное_покрытие.jpg"),
  product("sheet-chem-47", "chemistry", ["Ортофосфорная кислота", "Ортофосфор қышқылы", "Phosphoric acid"], "Казахстан", "АГМК", "H₃PO₄", "/images/Ортофосфорная_кислота.jpg"),
  product("sheet-chem-48", "chemistry", ["Лигносульфонат натрия", "Натрий лигносульфонаты", "Sodium lignosulfonate"], "Китай", "АГМК", "Полимер", "/images/Лигносульфонат_натрия.jpg"),
  product("sheet-chem-49", "chemistry", ["Молекулярное сито (цеолит)", "Молекулалық елек (цеолит)", "Molecular sieve (zeolite)"], "Китай", "АГМК", "Алюмосиликат", "/images/Молекулярное_сито.jpg"),
  product("sheet-chem-50", "chemistry", ["Активный и инертный оксид алюминия", "Белсенді және инертті алюминий оксиді", "Activated and inert alumina"], "Китай", "АГМК", "Al₂O₃", "/images/Активный_и_инертный_оксид_алюминия.jpg"),
  product("sheet-chem-51", "chemistry", ["Калий йодистый ЧДА, ХЧ", "Калий йодиді, ЧДА/ХЧ", "Potassium iodide, analytical/reagent grade"], "Россия", "АГМК", "KI", "/images/Калий_йодистый_ЧДА_ХЧ.jpg"),
  product("sheet-chem-54", "chemistry", ["Нитрат натрия (селитра натриевая)", "Натрий нитраты (натрий селитрасы)", "Sodium nitrate"], "Китай, РФ", "НГМК", "NaNO₃"),
  product("sheet-chem-56", "chemistry", ["Углеродосодержащий материал", "Көміртекті материал", "Carbonaceous material"], "Россия", "АГМК", "C", "/images/Углеродосодержащий_материал.jpg"),
  product("sheet-chem-58", "chemistry", ["Феррованадий", "Феррованадий", "Ferrovanadium"], "Китай", "АГМК", "FeV", "/images/Феррованадий.jpg"),
  product("sheet-chem-61", "chemistry", ["Аммоний сернистый 16–30%", "Аммоний сульфиді 16–30%", "Ammonium sulfide 16–30%"], "Китай", "АГМК", "(NH₄)₂S", "/images/Аммоний.jpg"),
  product("sheet-chem-62", "chemistry", ["Пероксид марганца", "Марганец пероксиді", "Manganese dioxide"], "Китай", "АГМК", "MnO₂"),

  // Metals and alloys selected in green in the source workbook.
  product("sheet-met-1", "metals", ["Нержавеющие трубы", "Тот баспайтын құбырлар", "Stainless steel pipes"], "Китай", "АГМК, НГМК, Узметкомбинат, Минэнерго, Нефтегаз", undefined, "/images/Нержавеющие_трубы.jpg"),
  product("sheet-met-2", "metals", ["Нержавеющие круги", "Тот баспайтын болат дөңгелектер", "Stainless steel rounds"], "Китай", "АГМК, НГМК", undefined, "/images/Нержавеющие_круги.jpg"),
  product("sheet-met-3", "metals", ["Стальные круги", "Болат дөңгелектер", "Steel rounds"], "Китай", "АГМК, НГМК", undefined, "/images/Стальные_круги.jpg"),
  product("sheet-met-4", "metals", ["Чёрные трубы", "Қара болат құбырлар", "Carbon steel pipes"], "Китай", "АГМК, НГМК, Узметкомбинат, Минэнерго, Нефтегаз", undefined, "/images/Чёрные_трубы.jpg"),
  product("sheet-met-5", "metals", ["Трубы КВД", "КВД құбырлары", "High-pressure pipes"], "Китай", "НГМК, Минэнерго", undefined, "/images/Трубы_КВД.jpg"),
  product("sheet-met-6", "metals", ["Нержавеющие листы", "Тот баспайтын болат табақтар", "Stainless steel sheets"], "Китай", "АГМК, НГМК, Минэнерго", undefined, "/images/Нержавеющие_листы.jpg"),
  product("sheet-met-10", "metals", ["Стойка шахтная СВП", "СВП шахталық тіреуі", "SVP mine support section"], "Китай", "АГМК, НГМК", undefined, "/images/Стойка_шахтная_СВП.jpg"),
  product("sheet-met-11", "metals", ["Сталь буровая шестигранная 55С2", "55С2 алты қырлы бұрғылау болаты", "55S2 hexagonal drill steel"], "Китай", "АГМК, НГМК", undefined, "/images/Сталь_буровая_шестигранная_55С2.jpg"),
  product("sheet-met-12", "metals", ["Калиброванный шестигранник 40Х", "40Х калибрленген алты қырлы болат", "40Kh calibrated hexagonal bar"], "Китай", "НГМК", undefined, "/images/Калиброванный_шестигранник_40Х.jpg"),
  product("sheet-met-14", "metals", ["Стальные канаты", "Болат арқандар", "Steel wire ropes"], "Россия/Китай", "АГМК, НГМК"),
  product("sheet-met-15", "metals", ["Поковки (вал-шестерня, цапфа и др.)", "Соғылмалар (білік-тістегершік, цапфа және т.б.)", "Forgings (gear shafts, trunnions, etc.)"], "Китай", "АГМК, НГМК, Узметкомбинат", undefined, "/images/Поковки_вал-шестерня_цапфа_и_др.jpg"),
  product("sheet-met-16", "metals", ["Лента стальная упаковочная", "Болат қаптама таспасы", "Steel strapping"], "Россия", "АГМК", undefined, "/images/Лента_стальная_упаковочная.jpg"),
  product("sheet-met-17", "metals", ["Ферромарганец", "Ферромарганец", "Ferromanganese"], "Китай", "АГМК, НГМК, Узметкомбинат"),
  product("sheet-met-18", "metals", ["Феррохром ФХ", "ФХ феррохромы", "Ferrochrome FKh"], "Россия", "АГМК, НГМК", undefined, "/images/Феррохром_ФХ.jpg"),
  product("sheet-met-19", "metals", ["Ферротитан", "Ферротитан", "Ferrotitanium"], "Россия", "АГМК, НГМК", undefined, "/images/Ферротитан.jpg"),
  product("sheet-met-20", "metals", ["Никель", "Никель", "Nickel"], "Африка", "АГМК, НГМК", undefined, "/images/Никель.jpg"),
  product("sheet-met-21", "metals", ["Чугун литейный и передельный", "Құю және қайта өңдеу шойыны", "Foundry and basic pig iron"], "Россия", "АГМК, НГМК", undefined, "/images/Чугун_литейный_и_передельный.jpg"),
  product("sheet-met-22", "metals", ["Чугунные валки", "Шойын біліктер", "Cast iron rolls"], "Китай", "Узметкомбинат"),
  product("sheet-met-23", "metals", ["Свинец в чушках", "Құйма қорғасын", "Lead ingots"], "Китай", "АГМК", undefined, "/images/Свинец_в_чушках.jpg"),
  product("sheet-met-24", "metals", ["Алюминиевые листы", "Алюминий табақтар", "Aluminum sheets"], "Китай", "АГМК, НГМК", undefined, "/images/Алюминиевые_листы.jpg"),
  product("sheet-met-25", "metals", ["Порошок алюминиевый", "Алюминий ұнтағы", "Aluminum powder"], "Россия", "АГМК"),
  product("sheet-met-26", "metals", ["Титановая продукция", "Титан өнімдері", "Titanium products"], "Китай", "АГМК, НГМК", undefined, "/images/Титановая_продукция.jpg"),
  product("sheet-met-27", "metals", ["Баббит и олово", "Баббит және қалайы", "Babbitt metal and tin"], "Россия", "АГМК", undefined, "/images/Баббит_и _олово.jpg"),
  product("sheet-met-28", "metals", ["Роли свинцовые", "Қорғасын роликтері", "Lead rollers"], "Чехия", "АГМК", undefined, "/images/Роли_свинцовые.jpg"),
  product("sheet-met-29", "metals", ["Медная плита", "Мыс плита", "Copper plate"], "Россия", "АГМК", undefined, "/images/Медная_плита.jpg"),
  product("sheet-met-30", "metals", ["Шины медные", "Мыс шиналар", "Copper busbars"], "Китай", "АГМК", undefined, "/images/Шины_медные.jpg"),
  product("sheet-met-31", "metals", ["Трубы медные ГКВНХ", "ГКВНХ мыс құбырлары", "GKVNKh copper tubes"], "Россия/Китай", "АГМК", undefined, "/images/Трубы_медные_ГКВНХ.jpg"),
  product("sheet-met-32", "metals", ["Окись кобальта", "Кобальт оксиді", "Cobalt oxide"], "Китай", "АГМК", undefined, "/images/Окись_кобальта.jpg"),
  product("sheet-met-33", "metals", ["Кварцит металлургический", "Металлургиялық кварцит", "Metallurgical quartzite"], "Китай", "АГМК, НГМК", undefined, "/images/кварцит_метал.jpg"),
  product("sheet-met-34", "metals", ["Модификатор стали", "Болат модификаторы", "Steel modifier"], "Россия", "АГМК"),
  product("sheet-met-35", "metals", ["Алюминиевые плиты", "Алюминий плиталар", "Aluminum plates"], "Китай", "АГМК", undefined, "/images/Алюминиевые_плиты.jpg"),
  product("sheet-met-36", "metals", ["Дробь стальная литая", "Құйма болат бытыра", "Cast steel shot"], "Китай", "АГМК"),

  // Equipment and components selected in green in the source workbook.
  product("sheet-equip-1", "equipment", ["Электроды графитированные", "Графиттелген электродтар", "Graphite electrodes"], "Китай", "АГМК, НГМК, Узметкомбинат, Казферросталь"),
  product("sheet-equip-2", "equipment", ["Сварочные электроды", "Дәнекерлеу электродтары", "Welding electrodes"], "Россия", "АГМК, НГМК, Минэнерго", undefined, "/images/Сварочные_электроды.jpg"),
  product("sheet-equip-3", "equipment", ["Шарошечные долота, долота PDC", "Шарошкалы қашаулар, PDC қашаулары", "Roller-cone bits and PDC bits"], "Россия", "АГМК, НГМК"),
  product("sheet-equip-4", "equipment", ["Автошины КГШ", "КГШ автодөңгелектері", "OTR tires"], "Китай", "АГМК, НГМК, Узбекуголь"),
  product("sheet-equip-6", "equipment", ["Автошины для подземной техники", "Жерасты техникасына арналған шиналар", "Tires for underground equipment"], "Китай", "АГМК, НГМК, Узбекуголь", undefined, "/images/Автошины_для_подземной_техники.jpg"),
  product("sheet-equip-7", "equipment", ["Рельсы", "Рельстер", "Rails"], "Китай", "АГМК, НГМК, Узметкомбинат", undefined, "/images/Рельсы.jpg"),
  product("sheet-equip-8", "equipment", ["Лента конвейерная", "Конвейер таспасы", "Conveyor belt"], "Китай", "АГМК, НГМК", undefined, "/images/Лента_конвейерная.jpg"),
  product("sheet-equip-10", "equipment", ["Шары кованые стальные", "Соғылған болат шарлар", "Forged steel balls"], "Россия/Китай", "АГМК, НГМК", undefined, "/images/Шары_кованые_стальные.jpg"),
  product("sheet-equip-11", "equipment", ["Компрессор воздушный", "Ауа компрессоры", "Air compressor"], "Китай", "АГМК, НГМК", undefined, "/images/Компрессор_воздушный.jpg"),
  product("added-equip-drilling-machine", "equipment", ["Буровой станок", "Бұрғылау станогы", "Drilling rig"], "", "", undefined, "/images/буровой_станок.jpg"),
  product("sheet-equip-12", "equipment", ["Венцы зубчатые", "Тісті тәждер", "Girth gears"], "Китай", "АГМК, НГМК"),
  product("sheet-equip-14", "equipment", ["Буровые штанги СБШ-250, НКР", "СБШ-250, НКР бұрғылау штангалары", "SBSh-250 and NKR drill rods"], "Китай", "НГМК, АГМК"),
  product("sheet-equip-15", "equipment", ["Бурильные трубы", "Бұрғылау құбырлары", "Drill pipes"], "Китай", "НГМК", undefined, "/images/Бурильные_трубы.jpg"),
  product("sheet-equip-16", "equipment", ["Буровые штанги конусные", "Конусты бұрғылау штангалары", "Tapered drill rods"], "Китай/Украина/Швеция", "АГМК, НГМК", undefined, "/images/Буровые_штанги_конусные.jpg"),
  product("sheet-equip-17", "equipment", ["Коронка буровая", "Бұрғылау коронкасы", "Drill bit crown"], "Китай", "НГМК", undefined, "/images/Коронка_буровая.jpg"),
  product("sheet-equip-18", "equipment", ["Флюс сварочный", "Дәнекерлеу флюсі", "Welding flux"], "Китай/Украина/Россия", "АГМК", undefined, "/images/Флюс_сварочный.jpg"),
  product("sheet-equip-19", "equipment", ["Проволока порошковая", "Ұнтақты сым", "Flux-cored wire"], "Китай", "АГМК", undefined, "/images/Проволока_порошковая.jpg"),
  product("sheet-equip-20", "equipment", ["Нихромовая проволока, лента", "Нихром сымы мен таспасы", "Nichrome wire and tape"], "Китай", "АГМК, НГМК"),
  product("sheet-equip-21", "equipment", ["Электродвигатели", "Электр қозғалтқыштары", "Electric motors"], "Россия/Украина/Китай", "АГМК, НГМК"),
  product("sheet-equip-22", "equipment", ["Тигли огнеупорные", "Отқа төзімді тигельдер", "Refractory crucibles"], "Россия", "АГМК, НГМК", undefined, "/images/Тигли_огнеупорные.jpg"),
  product("sheet-equip-23", "equipment", ["Шар стальной помольный", "Болат ұнтақтау шары", "Steel grinding balls"], "Россия/Китай", "АГМК, НГМК", undefined, "/images/Шар_стальной_помольный.jpg"),
  product("sheet-equip-24", "equipment", ["Запорная арматура", "Жапқыш арматура", "Shut-off valves"], "Россия/Китай", "АГМК/Минэнерго", undefined, "/images/Запорная_арматура.jpg"),
  product("sheet-equip-27", "equipment", ["Электровозы", "Электровоздар", "Electric locomotives"], "Россия/Украина", "АГМК, НГМК", undefined, "/images/Электровозы.jpg"),
  product("sheet-equip-30", "equipment", ["Кислородные и азотные станции и установки", "Оттегі және азот станциялары мен қондырғылары", "Oxygen and nitrogen plants and units"], "Россия/Китай", "НГМК, АГМК", undefined, "/images/Кислородные_и_азотные_станции_и_установки.jpg"),
  product("sheet-equip-31", "equipment", ["Фрезерный станок", "Фрезерлік станок", "Milling machine"], "Китай", "АГМК", undefined, "/images/Фрезерный_станок.jpg"),
  product("sheet-equip-32", "equipment", ["Круглошлифовальный станок", "Дөңгелек тегістеу станогы", "Cylindrical grinding machine"], "Китай", "УЗЖД", undefined, "/images/Круглошлифовальный_станок.jpg"),
  product("sheet-equip-33", "equipment", ["Строгальный станок", "Сүргілеу станогы", "Planing machine"], "Китай", "УЗЖД", undefined, "/images/Строгальный_станок.jpg"),
  product("sheet-equip-34", "equipment", ["Токарно-фрезерный станок", "Токарлық-фрезерлік станок", "Turn-mill machine"], "Япония", "АГМК, НГМК", undefined, "/images/Токарно-фрезерный_станок.jpg"),
  product("sheet-equip-35", "equipment", ["Токарно-винторезные станки", "Токарлық-бұранда кескіш станоктар", "Screw-cutting lathes"], "Китай", "АГМК, НГМК, Узметкомбинат", undefined, "/images/Токарно-винторезные_станки.jpg"),
  product("sheet-equip-36", "equipment", ["Сверлильный станок", "Бұрғылау станогы", "Drilling machine"], "Китай", "АГМК, НГМК", undefined, "/images/Сверлильный_станок.jpg"),
  product("sheet-equip-37", "equipment", ["Радиально-сверлильный станок", "Радиалды бұрғылау станогы", "Radial drilling machine"], "Китай", "АГМК, НГМК", undefined, "/images/Радиально-сверлильный_станок.jpg"),
  product("sheet-equip-38", "equipment", ["Кромкооблицовочный станок", "Жиек қаптау станогы", "Edge-banding machine"], "Китай", "АГМК", undefined, "/images/Кромкооблицовочный_станок.jpg"),
  product("sheet-equip-39", "equipment", ["Шлифовальный станок", "Тегістеу станогы", "Grinding machine"], "Япония", "АГМК, НГМК", undefined, "/images/Шлифовальный_станок.jpg"),
  product("sheet-equip-40", "equipment", ["Станок газовой и плазменной резки", "Газды және плазмалық кесу станогы", "Gas and plasma cutting machine"], "Китай", "АГМК", undefined, "/images/Станок_газовой_и_плазменной_резки.jpg"),
  product("sheet-equip-41", "equipment", ["Маркировочный станок", "Таңбалау станогы", "Marking machine"], "Россия/Китай", "АГМК", undefined, "/images/Маркировочный_станок.jpg"),
  product("sheet-equip-42", "equipment", ["Долбёжный станок", "Ойық кесу станогы", "Slotting machine"], "Россия", "АГМК", undefined, "/images/Долбёжный_станок.jpg"),
  product("sheet-equip-43", "equipment", ["Фуговальный станок", "Фуговкалау станогы", "Jointer machine"], "Китай", "АГМК", undefined, "/images/Фуговальный_станок.jpg"),
  product("sheet-equip-44", "equipment", ["Пресс гидравлический вулканизационный", "Гидравликалық вулканизациялық пресс", "Hydraulic vulcanizing press"], "Китай", "АГМК, НГМК", undefined, "/images/Пресс_гидравлический_вулканизационный.jpg"),
  product("sheet-equip-45", "equipment", ["Ножницы механические", "Механикалық қайшылар", "Mechanical shears"], "Китай", "АГМК", undefined, "/images/Ножницы_механические.jpg"),
  product("sheet-equip-46", "equipment", ["Горизонтально-ковочная машина", "Көлденең соғу машинасы", "Horizontal forging machine"], "Китай", "АГМК", undefined, "/images/Горизонтально-ковочная_машина.jpg"),
  product("sheet-equip-47", "equipment", ["Манипулятор ковочный мобильный", "Жылжымалы соғу манипуляторы", "Mobile forging manipulator"], "Корея", "АГМК", undefined, "/images/Манипулятор_ковочный_мобильный.jpg"),
  product("sheet-equip-48", "equipment", ["Молот ковочный пневматический", "Пневматикалық соғу балғасы", "Pneumatic forging hammer"], "Китай", "АГМК", undefined, "/images/Молот_ковочный_пневматический.jpg"),
  product("sheet-equip-49", "equipment", ["Домкраты гидравлические", "Гидравликалық домкраттар", "Hydraulic jacks"], "Китай", "АГМК", undefined, "/images/Домкраты_гидравлические.jpg"),
  product("sheet-equip-53", "equipment", ["Зубофрезерный станок", "Тісті фрезерлеу станогы", "Gear hobbing machine"], "Китай", "НГМК", undefined, "/images/Зубофрезерный_станок.jpg"),
  product("sheet-equip-58", "equipment", ["Обжимной станок", "Қысу станогы", "Crimping machine"], "Китай", "НГМК", undefined, "/images/Обжимной_станок.jpg"),
  product("sheet-equip-59", "equipment", ["Станок для навязки пожарных рукавов", "Өрт сөндіру жеңдерін байлау станогы", "Fire-hose coupling machine"], "Китай", "НГМК", undefined, "/images/Станок_для_навязки_пожарных_рукавов.jpg"),
  product("sheet-equip-60", "equipment", ["Шаровая мельница", "Шарлы диірмен", "Ball mill"], "Китай", "АГМК", undefined, "/images/Шаровая_мельница.jpg"),
  product("sheet-equip-61", "equipment", ["Пресс гидравлический насадочный", "Гидравликалық отырғызу пресі", "Hydraulic mounting press"], "Китай", "НГМК", undefined, "/images/Пресс_гидравлический_насадочный.jpg"),
  {
    id: "sheet-equip-65",
    category: "equipment",
    name: localized("Конусная дробилка", "Конусты ұсатқыш", "Cone crusher"),
    description: localized(
      "Промышленная конусная дробилка для вторичного и третичного дробления горных пород и минерального сырья. Модель и параметры подбираются под требуемую производительность и фракцию готового материала.",
      "Тау жыныстары мен минералдық шикізатты екінші және үшінші сатылы ұсақтауға арналған өнеркәсіптік конусты ұсатқыш. Үлгісі мен параметрлері қажетті өнімділікке және дайын материал фракциясына сәйкес таңдалады.",
      "Industrial cone crusher for secondary and tertiary crushing of rock and mineral raw materials. The model and parameters are selected for the required capacity and final product size.",
    ),
    origin: "Китай",
    buyer: "АГМК, НГМК",
    image: "/images/Конусная_дробилка.jpg",
    detailTables: [
      detailTable(
        localized(
          "Одноцилиндровая конусная дробилка серии GPL",
          "GPL сериялы бір цилиндрлі конусты ұсатқыш",
          "GPL Series Single-Cylinder Cone Crusher",
        ),
        [
          localized("Модель", "Үлгі", "Model"),
          localized(
            "Максимальный размер подаваемого материала (мм)",
            "Берілетін материалдың ең үлкен өлшемі (мм)",
            "Maximum feed size (mm)",
          ),
          localized(
            "Размер выходного отверстия (мм)",
            "Шығару саңылауының өлшемі (мм)",
            "Discharge opening size (mm)",
          ),
          localized(
            "Мощность (кВт)",
            "Қуаты (кВт)",
            "Power (kW)",
          ),
        ],
        [
          [technical("GPL100S"), technical("210"), technical("20–45"), technical("90")],
          [technical("GPL200S"), technical("290"), technical("25–50"), technical("160")],
          [technical("GPL300S"), technical("330"), technical("25–50"), technical("250")],
          [technical("GPL500S"), technical("440"), technical("45–80"), technical("355")],
          [technical("GPL100"), technical("135"), technical("7–25"), technical("90")],
          [technical("GPL200"), technical("180"), technical("8–35"), technical("160")],
          [technical("GPL300"), technical("190"), technical("8–35"), technical("250")],
          [technical("GPL550"), technical("235"), technical("10–45"), technical("400")],
        ],
      ),
      detailTable(
        localized(
          "Многоцилиндровая конусная дробилка серии HPL",
          "HPL сериялы көп цилиндрлі конусты ұсатқыш",
          "HPL Series Multi-Cylinder Cone Crusher",
        ),
        [
          localized("Модель дробилки", "Ұсатқыш үлгісі", "Crusher model"),
          localized(
            "Диаметр конуса (мм)",
            "Конустың диаметрі (мм)",
            "Head diameter (mm)",
          ),
          localized(
            "Мощность главного электродвигателя (кВт)",
            "Негізгі электр қозғалтқышының қуаты (кВт)",
            "Main motor power (kW)",
          ),
          localized("Масса (т)", "Массасы (т)", "Weight (t)"),
        ],
        [
          [technical("HPL100"), technical("735"), technical("90"), technical("6.4")],
          [technical("HPL200"), technical("940"), technical("132"), technical("12.1")],
          [technical("HPL300"), technical("1120"), technical("220"), technical("18.1")],
          [technical("HPL400"), technical("1320"), technical("315"), technical("25.6")],
          [technical("HPL500"), technical("1520"), technical("355"), technical("37")],
          [technical("HPL800"), technical("1650"), technical("600"), technical("64.1")],
        ],
      ),
      detailTable(
        localized(
          "Одноцилиндровая конусная дробилка серии CHL–CSL",
          "CHL–CSL сериялы бір цилиндрлі конусты ұсатқыш",
          "CHL–CSL Series Single-Cylinder Cone Crusher",
        ),
        [
          localized("Модель", "Үлгі", "Model"),
          localized(
            "Максимальный размер загрузочного материала (мм)",
            "Жүктелетін материалдың ең үлкен өлшемі (мм)",
            "Maximum feed size (mm)",
          ),
          localized(
            "Размер выходного отверстия (мм)",
            "Шығару саңылауының өлшемі (мм)",
            "Discharge opening size (mm)",
          ),
          localized(
            "Мощность (кВт)",
            "Қуаты (кВт)",
            "Power (kW)",
          ),
        ],
        [
          [technical("CSL420"), technical("267"), technical("16–38"), technical("90")],
          [technical("CSL430"), technical("400"), technical("16–83"), technical("132")],
          [technical("CSL440"), technical("500"), technical("29–83"), technical("220")],
          [technical("CSL660"), technical("622"), technical("35–83"), technical("315")],
          [technical("CHL420"), technical("155"), technical("4–32"), technical("90")],
          [technical("CHL430"), technical("214"), technical("4–70"), technical("132")],
          [technical("CHL440"), technical("250"), technical("4–44"), technical("220")],
          [technical("CHL660"), technical("321"), technical("13–70"), technical("315")],
          [technical("CHL860i"), technical("315"), technical("13–51"), technical("500")],
          [technical("CHL870i"), technical("350"), technical("10–70"), technical("600")],
        ],
      ),
      detailTable(
        localized(
          "Пружинная конусная дробилка",
          "Серіппелі конусты ұсатқыш",
          "Spring Cone Crusher",
        ),
        [
          localized("Модель", "Үлгі", "Model"),
          localized(
            "Диаметр дробящего конуса (мм)",
            "Ұсатқыш конустың диаметрі (мм)",
            "Crushing cone diameter (mm)",
          ),
          localized(
            "Максимальный размер подаваемого материала (мм)",
            "Берілетін материалдың ең үлкен өлшемі (мм)",
            "Maximum feed size (mm)",
          ),
          localized(
            "Мощность электродвигателя (кВт)",
            "Электр қозғалтқышының қуаты (кВт)",
            "Electric motor power (kW)",
          ),
        ],
        [
          [technical("PYB900"), technical("900"), technical("115"), technical("55")],
          [technical("PYZ900"), technical("900"), technical("60"), technical("55")],
          [technical("PYD900"), technical("900"), technical("50"), technical("55")],
          [technical("PYB1200"), technical("1200"), technical("145"), technical("110")],
          [technical("PYZ1200"), technical("1200"), technical("100"), technical("110")],
          [technical("PYD1200"), technical("1200"), technical("50"), technical("110")],
          [technical("PYB1200"), technical("1200"), technical("100"), technical("160")],
          [technical("PYZ1750"), technical("1750"), technical("185"), technical("160")],
          [technical("PYD1750"), technical("1750"), technical("85"), technical("160")],
          [technical("PYB2200"), technical("2200"), technical("300"), technical("280")],
          [technical("PYD2200"), technical("2200"), technical("100"), technical("280")],
        ],
      ),
    ],
  },
  {
    id: "added-equip-jaw-crusher",
    category: "equipment",
    name: localized("Щековая дробилка", "Жақты ұсатқыш", "Jaw crusher"),
    description: localized(
      "Промышленная щековая дробилка для первичного и вторичного дробления горных пород и минерального сырья. Модель и технические параметры подбираются под требуемую производительность.",
      "Тау жыныстары мен минералдық шикізатты бастапқы және қайталама ұсақтауға арналған өнеркәсіптік жақты ұсатқыш. Үлгісі мен техникалық параметрлері қажетті өнімділікке сәйкес таңдалады.",
      "Industrial jaw crusher for primary and secondary crushing of rock and mineral raw materials. The model and technical parameters are selected for the required capacity.",
    ),
    image: "/images/Щековая_дробилка.jpg",
    detailTables: [
      detailTable(
        localized(
          "Щековая дробилка серии CL",
          "CL сериялы жақты ұсатқыш",
          "CL Series Jaw Crusher",
        ),
        [
          localized("Модель", "Үлгі", "Model"),
          localized(
            "Размер приёмного отверстия (мм×мм)",
            "Қабылдау саңылауының өлшемі (мм×мм)",
            "Feed opening size (mm×mm)",
          ),
          localized(
            "Планируемый максимальный размер подаваемого материала (мм)",
            "Берілетін материалдың жоспарлы ең үлкен өлшемі (мм)",
            "Planned maximum feed size (mm)",
          ),
          localized(
            "Производительность (Mtph)",
            "Өнімділігі (Mtph)",
            "Capacity (Mtph)",
          ),
        ],
        [
          [technical("CL80"), technical("800×510"), technical("410"), technical("245")],
          [technical("CL96"), technical("930×580"), technical("460"), technical("310")],
          [technical("CL106"), technical("1060×700"), technical("560"), technical("395")],
          [technical("CL110"), technical("1100×850"), technical("680"), technical("430")],
          [technical("CL120"), technical("1200×870"), technical("700"), technical("395")],
          [technical("CL125"), technical("1250×950"), technical("760"), technical("590")],
          [technical("CL130"), technical("1300×1000"), technical("800"), technical("605")],
          [technical("CL145"), technical("1400×1100"), technical("870"), technical("625")],
          [technical("CL150"), technical("1400×1200"), technical("960"), technical("640")],
          [technical("CL160"), technical("1600×1200"), technical("960"), technical("815")],
          [technical("CL200"), technical("2000×1500"), technical("1200"), technical("1015")],
        ],
      ),
      detailTable(
        localized(
          "Щековая дробилка серии PE",
          "PE сериялы жақты ұсатқыш",
          "PE Series Jaw Crusher",
        ),
        [
          localized("Модель", "Үлгі", "Model"),
          localized(
            "Размер входного отверстия (мм×мм)",
            "Кіріс саңылауының өлшемі (мм×мм)",
            "Feed opening size (mm×mm)",
          ),
          localized(
            "Максимальный размер загружаемого материала (мм)",
            "Жүктелетін материалдың ең үлкен өлшемі (мм)",
            "Maximum feed size (mm)",
          ),
          localized(
            "Производительность (т/ч)",
            "Өнімділігі (т/сағ)",
            "Capacity (t/h)",
          ),
        ],
        [
          [technical("PE-150×250"), technical("150×250"), technical("130"), technical("1–5")],
          [technical("PE-250×400"), technical("250×400"), technical("210"), technical("5–20")],
          [technical("PE-250×750"), technical("250×750"), technical("210"), technical("13–35")],
          [technical("PE-250×1000"), technical("250×1000"), technical("210"), technical("16–52")],
          [technical("PE-250×1200"), technical("250×1200"), technical("210"), technical("20–60")],
          [technical("PE-300×500"), technical("300×500"), technical("250"), technical("5–20")],
          [technical("PE-300×1300"), technical("300×1300"), technical("250"), technical("16–104")],
          [technical("PE-400×600"), technical("400×600"), technical("340"), technical("16–65")],
          [technical("PE-500×700"), technical("500×700"), technical("425"), technical("45–100")],
          [technical("PE-600×900"), technical("600×900"), technical("500"), technical("50–120")],
          [technical("PE-750×1060"), technical("750×1060"), technical("630"), technical("52–208")],
          [technical("PE-800×1060"), technical("800×1060"), technical("650"), technical("85–228")],
          [technical("PE-870×1060"), technical("870×1060"), technical("670"), technical("181–280")],
          [technical("PE-900×1200"), technical("900×1200"), technical("750"), technical("140–320")],
          [technical("PE-1000×1200"), technical("1000×1200"), technical("850"), technical("160–350")],
          [technical("PE-1200×1500"), technical("1200×1500"), technical("1020"), technical("300–800")],
          [technical("PE-1500×1800"), technical("1500×1800"), technical("1200"), technical("430–1000")],
        ],
      ),
    ],
  },
  product("sheet-equip-66", "equipment", ["Запчасти для автогрейдеров, тракторов и бульдозеров", "Автогрейдерлерге, тракторлар мен бульдозерлерге арналған қосалқы бөлшектер", "Spare parts for motor graders, tractors, and bulldozers"], "Россия/Китай", "АГМК, НГМК", undefined, "/images/Запчасти_для_автогрейдеров_тракторов_и_бульдозеров.jpg"),
  product("sheet-equip-67", "equipment", ["Запчасти к станкам и автотехнике", "Станоктар мен автотехникаға арналған қосалқы бөлшектер", "Spare parts for machine tools and vehicles"], "Россия/Китай", "АГМК, НГМК", undefined, "/images/Запчасти_к_станкам_и_автотехнике.jpg"),
  product("sheet-equip-68", "equipment", ["Запчасти промышленных мельниц, дробилок, печей и барабанов", "Өнеркәсіптік диірмендерге, ұсатқыштарға, пештер мен барабандарға арналған қосалқы бөлшектер", "Spare parts for industrial mills, crushers, furnaces, and drums"], "Китай", "НГМК, АГМК", undefined, "/images/Запчасти_промышленных_мельниц_дробилок_печей_и_барабанов.jpg"),
  product("sheet-equip-69", "equipment", ["Запчасти для проходческого комплекса КПВ-4А", "КПВ-4А проходкалау кешеніне арналған қосалқы бөлшектер", "Spare parts for KPV-4A tunneling complex"], "Россия", "АГМК", undefined, "/images/Запчасти_для_проходческого_комплекса_КПВ-4А.jpg"),
  product("sheet-equip-71", "equipment", ["Шпалы деревянные, брусья переводные", "Ағаш шпалдар және бағыттамалық брустар", "Wooden sleepers and switch timbers"], "Россия", "АГМК", undefined, "/images/Шпалы_деревянные_брусья_переводные.jpg"),
  product("sheet-equip-72", "equipment", ["Редукторы", "Редукторлар", "Gearboxes"], "Китай", "АГМК, НГМК", undefined, "/images/Редукторы.jpg"),
  product("sheet-equip-73", "equipment", ["Мотор-редуктор", "Мотор-редуктор", "Geared motor"], "Россия/Китай", "АГМК", undefined, "/images/Мотор-редуктор.jpg"),
  product("sheet-equip-74", "equipment", ["Экзотермические вставки", "Экзотермиялық кірістірмелер", "Exothermic inserts"], "Россия", "АГМК", undefined, "/images/Экзотермические_вставки.jpg"),
  product("sheet-equip-75", "equipment", ["Абразивоструйная камера", "Абразивті ағын камерасы", "Abrasive blasting chamber"], "Россия", "АГМК", undefined, "/images/Абразивоструйная_камера.jpg"),
  product("sheet-equip-76", "equipment", ["Контроллеры КС", "КС контроллерлері", "KS controllers"], "Россия", "АГМК", undefined, "/images/Контроллеры_КС.jpg"),
  product("sheet-equip-77", "equipment", ["Пружины для вагонеток", "Вагонеткаларға арналған серіппелер", "Mine-cart springs"], "Китай", "АГМК", undefined, "/images/Пружины_для_вагонеток.jpg"),
  product("sheet-equip-78", "equipment", ["Цепь катодомоечной машины", "Катод жуу машинасының тізбегі", "Cathode-washing machine chain"], "Россия", "АГМК", undefined, "/images/Цепь_катодомоечной_машины.jpg"),
  product("sheet-equip-79", "equipment", ["Цепи приводные роликовые любой сложности", "Кез келген күрделіліктегі роликті жетек тізбектері", "Roller drive chains of any complexity"], "Россия", "АГМК, НГМК, Узметкомбинат", undefined, "/images/Цепи_приводные_роликовые_любой_сложности.jpg"),
  product("sheet-equip-93", "equipment", ["Грейфер", "Грейфер", "Grab bucket"], "Китай", "АГМК", undefined, "/images/Грейфер.jpg"),
  product("sheet-equip-94", "equipment", ["Трубка кварцевая", "Кварц түтігі", "Quartz tube"], "Россия", "АГМК", undefined, "/images/Трубка_кварцевая.jpg"),
  product("sheet-equip-95", "equipment", ["Роли свинцовые", "Қорғасын роликтері", "Lead rollers"], "Чехия", "АГМК"),
  product("sheet-equip-96", "equipment", ["Грохот двухъярусный для сухого разделения", "Құрғақ бөлуге арналған екі қабатты елек", "Double-deck screen for dry separation"], "Россия", "АГМК", undefined, "/images/Грохот_двухъярусный_для_сухого_разделения.jpg"),
  product("sheet-equip-100", "equipment", ["Вал-звёздочка с редуктором для пластинчатых питателей", "Пластиналы қоректендіргіштерге арналған редукторлы жұлдызша-білік", "Sprocket shaft with gearbox for apron feeders"], "Китай", "АГМК", undefined, "/images/Вал-звёздочка_с_редуктором_для_пластинчатых_питателей.jpg"),
  product("sheet-equip-103", "equipment", ["Ковши экскаваторов", "Экскаватор шөміштері", "Excavator buckets"], "Китай", "АГМК", undefined, "/images/Ковши_экскаваторов.jpg"),
  product("sheet-equip-104", "equipment", ["Прокатные валки", "Прокат біліктері", "Rolling mill rolls"], "Китай", "Узметкомбинат"),
  product("sheet-equip-106", "equipment", ["Вентиляторы", "Желдеткіштер", "Industrial fans"], "Россия", "АГМК, НГМК", undefined, "/images/Вентиляторы.jpg"),
]
